// ============================================================
// Mahmoud Abdallah — Portfolio Data
// Source: CV (March 2026) — reviewed and accurate
// ============================================================

export const personal = {
  name: "Mahmoud Abdallah",
  tagline: "Procurement, Supply Chain & Operations Professional",
  subtitle: "Built to solve. Built to build.",
  badge: "Open to Opportunities",
  email: "mahmoudf.abdallah@outlook.com",
  phone: "+971544720857",
  whatsapp: "https://wa.me/971544720857",
  linkedin: "https://www.linkedin.com/in/mahmoudf-abdallah",
  location: "Dubai, UAE",
  nationality: "Egyptian",
} as const;

export const hero = {
  typingWords: [
    "strategic sourcing",
    "vendor negotiations",
    "tender management",
    "ERP implementation",
    "supply chain optimization",
    "cost reduction strategies",
    "process automation",
    "contract management",
  ],
  stats: [
    { value: "7+ Years", label: "Procurement, Supply Chain & Operations" },
    { value: "Millions Saved", label: "Through Strategic Sourcing" },
    { value: "Hundreds of Vendors", label: "Sourced, Evaluated & Managed" },
    { value: "Multiple Industries", label: "Events · Equipment · FMCG · Oil & Gas · Retail · Trading" },
  ],
} as const;

export const about = {
  heading: "The Full Picture",
  sections: [
    {
      label: "Who I Am",
      text: "7+ years in procurement, supply chain, and operations across the GCC and Egypt. I've worked FMCG, oil & gas, event technology, and heavy equipment — and in every company, I left behind systems, results, and impact that didn't exist before I walked in.",
    },
    {
      label: "What I Do",
      text: "Full procurement lifecycle — from sourcing strategy and vendor negotiations to contract execution and source-to-pay. I manage RFQ cycles, evaluate and develop suppliers, and track vendor performance to drive continuous improvement. On the supply chain and operations side, I design workflows, streamline processes, and drive cross-functional alignment.",
    },
    {
      label: "What Sets Me Apart",
      text: "Beyond procurement, I build the operational backbone — SOPs, governance frameworks, compliance policies, and process automation powered by AI-driven workflows. I lead digital transformation initiatives including ERP implementations and system design. I also leverage vibe coding — AI-assisted development — to rapidly build internal tools, dashboards, and automation scripts that solve real operational problems. And I support business growth by managing the full bid lifecycle and equipping teams with the structure and tools they need to win contracts and scale.",
    },
  ],
  tags: ["Dubai, UAE", "7+ Years", "6 Industries", "GCC & Egypt", "Arabic & English", "Budgets up to AED 10M"],
} as const;

export const experience = [
  {
    role: "Procurement & Supply Chain Operations Manager",
    company: "Golden Sparrow Trading Co",
    type: "Heavy Equipment · Dubai",
    logo: "/images/newGoldenSparrowLogo.webp",
    period: "Oct 2025 — Present",
    location: "Dubai, UAE",
    current: true,
    promotion: "Promoted from Procurement & Tender Expert · 3 months",
    description: "Built the operations function from scratch — procurement infrastructure, ERP implementation, governance frameworks, and financing control structures under UAE law. Leading digital transformation, process automation, and cross-functional execution across sales, finance, and operations.",
    tags: ["Operations", "Odoo ERP", "Policy Design", "Digital Transformation"],
  },
  {
    role: "Procurement Process Executive",
    company: "Americana Foods",
    type: "FMCG Enterprise (20+ Markets) · Dubai",
    logo: "/images/americana_foods_logo.jpeg",
    period: "Apr 2025 — Oct 2025",
    location: "Dubai, UAE",
    current: false,
    description: "Managed procure-to-pay operations and master data governance across 20+ MENA markets — SKU harmonization, data migration, and process standardization at enterprise scale.",
    tags: ["Oracle", "Coupa", "Master Data", "P2P", "Enterprise Scale"],
  },
  {
    role: "Procurement & Tender Executive",
    company: "Fractal Systems",
    type: "Event Technology — LED, Kinetic, AV, Facade · Dubai",
    logo: "/images/fractal_systems_logo.jpeg",
    period: "Jan 2024 — Apr 2025",
    location: "Dubai, UAE",
    current: false,
    description: "Led procurement across 30+ high-profile projects — from mega events like World Defense Show, IKTVA, and LEAP, to permanent facade installations for Bank AlBilad and MOIAT, and immersive AV experiences for Red Sea Global and Dubai Chamber. Contract negotiations, vendor performance management, and spend optimization on budgets up to AED 10M.",
    tags: ["Events Tech", "Strategic Sourcing", "LED/AV", "Tenders", "Cost Optimization"],
  },
  {
    role: "Procurement & Logistics Officer",
    company: "Hafa Trading Co",
    type: "Oil & Gas Industrial Supplies · Al Khobar, KSA",
    logo: "/images/hafa_trading_co_logo.jpeg",
    period: "Aug 2021 — Jun 2023",
    location: "Al Khobar, KSA",
    current: false,
    description: "Managed end-to-end procurement and international logistics supporting Aramco, McDermott, and Schlumberger — covering RFQ cycles, vendor evaluation, cross-border compliance, and supplier relationship management across the GCC.",
    tags: ["Oil & Gas", "Logistics", "SABER", "Etimad", "Odoo"],
  },
  {
    role: "E-Commerce Buyer",
    company: "Saudi Supplier",
    type: "Industrial E-Commerce Marketplace · Remote, KSA",
    logo: "/images/saudi-supplier.jpeg",
    period: "Jul 2021 — Apr 2023",
    location: "Remote (KSA)",
    current: false,
    description: "Drove market intelligence, price benchmarking, and cost optimization across industrial product lines — procurement reporting and spend analysis to support commercial decisions within a B2B marketplace.",
    tags: ["E-Commerce", "Sourcing", "Market Analysis", "Cost Reduction"],
  },
  {
    role: "Supply Chain Coordinator",
    company: "Retail Stores of Second Egyptian Army",
    type: "FMCG Retail — 17 Branches · Egypt",
    logo: "/images/Egyptian_Armed_Forces_Logo.png",
    period: "Nov 2019 — Jan 2021",
    location: "Egypt",
    current: false,
    description: "Coordinated supply chain operations across 17 branches — demand planning, inventory control, fleet optimization, and supplier distribution management.",
    tags: ["Supply Chain", "Inventory", "Fleet Management", "FMCG Retail"],
  },
  {
    role: "AI Training Data Analyst & Model Evaluator — Sourcing & Procurement",
    company: "TELUS International · Appen · Figure Eight · CrowdFlower · Lionbridge AI",
    companies: ["TELUS International", "Appen", "Figure Eight", "CrowdFlower", "Lionbridge AI"],
    type: "Part-time · Remote",
    logo: "",
    period: "2017 — 2022",
    location: "Remote",
    current: false,
    earlier: true,
    badge: "FREELANCE",
    description:
      "Contributed to commercial AI & machine learning systems long before the technology went mainstream — working across multiple global AI & machine learning data platforms on model training and evaluation spanning procurement-specific datasets — product categorization, supplier sourcing, company profiling, and e-commerce search relevance. The work required judgment and consistency to translate real-world complexity into reliable training data that improved how models classified, matched, and ranked at scale.",
    tags: ["Data Annotation", "Model Evaluation", "Search Relevance", "Supplier Profiling", "AI & Machine Learning"],
  },
] as const;

export const projects = [
  {
    title: "Red Sea Global — Experience Center",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "Permanent AV installation for Red Sea Global's experience center — immersive technology showcasing the luxury giga-project tourism vision to investors and VIP guests.",
    highlights: [
      "Permanent immersive AV installation for Red Sea Global",
      "Multi-vendor coordination across AV, LED, and interactive tech",
    ],
    tools: ["Immersive AV", "Experience Center", "LED", "Permanent Install"],
    featured: true,
    image: "/images/projects/red-sea-global/thumbnail.jpg" as string | null,
    video: "https://www.youtube.com/watch?v=3wVnQQCHVog",
    gallery: [] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "Bank AlBilad — Facade Lighting",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "52-meter LED media facade using flexible LED strips — turn-key from design to execution. Dynamic branded content from Eid greetings to corporate messaging for Bank AlBilad HQ, Riyadh.",
    highlights: [
      "52-meter LED media facade — flexible LED strip technology",
      "Turn-key: design, fabrication, installation & content",
      "Dynamic branded content for Eid, corporate events & identity",
    ],
    tools: ["LED Facade", "Flexible LED", "Facade Lighting", "Riyadh"],
    featured: false,
    image: "/images/projects/bank-albilad/photo-1.jpeg" as string | null,
    video: "https://www.youtube.com/watch?v=Gq9lWsSYU-k",
    gallery: [
      "/images/projects/bank-albilad/photo-1.jpeg",
      "/images/projects/bank-albilad/photo-2.jpeg",
      "/images/projects/bank-albilad/photo-3.jpeg",
      "/images/projects/bank-albilad/photo-4.jpeg",
    ] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "IKTVA 2025",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "Anamorphic 3D content showcasing Aramco's '1st Made in Kingdom Products' — depth-illusion industrial plant model on LED displays at Saudi Aramco's flagship procurement event.",
    highlights: [
      "Anamorphic 3D depth-illusion of industrial manufacturing plant",
      "Showcasing Aramco's '1st Made in Kingdom Products' campaign",
    ],
    tools: ["Anamorphic 3D", "LED Displays", "Saudi Aramco"],
    featured: false,
    image: "/images/projects/iktva-2025/thumbnail.jpg" as string | null,
    video: "https://www.youtube.com/watch?v=VMfeyqfny68",
    gallery: [] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "COP16 — UNCCD",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "Mixed reality AR tablets and interactive pressure tiles — tech-forward engagement for global environmental delegates at the UN's desertification summit, Riyadh.",
    highlights: [
      "Mixed reality AR tablets for delegate engagement",
      "Interactive pressure tiles — responsive floor experience",
      "UN Convention on Combating Desertification — COP16 Riyadh",
    ],
    tools: ["AR/MR", "Interactive Tiles", "Projection Mapping", "UN Summit"],
    featured: false,
    image: "/images/projects/cop16-unccd/thumbnail.jpg" as string | null,
    video: "https://www.youtube.com/watch?v=zT4BY9Vz23s",
    gallery: [
      "/images/projects/cop16-unccd/thumbnail.jpg",
    ] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "1001 Seasons of Elie Saab",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "Procured 10 rotating 12m LED towers for Elie Saab's 45th anniversary show at Diriyah Season, Riyadh — featuring Celine Dion & Jennifer Lopez. Won 'Best Use of Technology', Saudi Event Awards 2025.",
    highlights: [
      "10 × 12-meter rotating LED towers, Diriyah Season Riyadh",
      "Winner — Best Use of Technology, Saudi Event Awards 2025",
      "Headline performers: Celine Dion & Jennifer Lopez",
    ],
    tools: ["LED Towers", "Kinetic Systems", "Riyadh", "Mega Event"],
    featured: true,
    image: null as string | null,
    video: "https://www.youtube.com/watch?v=tgdMYm1RA3o",
    gallery: [] as string[],
    stat: { value: "★", label: "Saudi Event Awards 2025" },
  },
  {
    title: "JETEX LED Cube — COP28",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "World's largest LED cube — 10m × 10m × 10m — designed, fabricated, and installed in 7 days to welcome world leaders at COP28, Dubai. Anamorphic 3D content creating immersive illusions at scale. (Maintenance & logistics support role.)",
    highlights: [
      "World's largest LED cube: 10m × 10m × 10m",
      "Full design, fabrication & installation in 7 days",
      "Anamorphic 3D content for COP28 world leaders",
    ],
    tools: ["LED Cube", "Anamorphic 3D", "COP28", "Dubai"],
    featured: true,
    image: "/images/projects/jetex-cop28/photo-1.jpeg" as string | null,
    video: "https://www.youtube.com/watch?v=d_WBUPegHP0",
    gallery: [
      "/images/projects/jetex-cop28/photo-1.jpeg",
      "/images/projects/jetex-cop28/photo-3.png",
      "/images/projects/jetex-cop28/photo-4.png",
      "/images/projects/jetex-cop28/photo-5.png",
      "/images/projects/jetex-cop28/photo-6.png",
      "/images/projects/jetex-cop28/photo-7.png",
      "/images/projects/jetex-cop28/photo-8.png",
      "/images/projects/jetex-cop28/photo-9.png",
      "/images/projects/jetex-cop28/photo-10.png",
      "/images/projects/jetex-cop28/photo-11.png",
      "/images/projects/jetex-cop28/photo-12.png",
      "/images/projects/jetex-cop28/photo-13.png",
      "/images/projects/jetex-cop28/photo-14.png",
    ] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "MA'ADEN Mining — Kinetic Cube",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "Multi-level kinetic cube with 3D animated journey — transforming a technical mining brief into a visual narrative about Saudi Arabia's mineral wealth for MA'ADEN. Showcased at a mining exhibition in Germany.",
    highlights: [
      "Multi-level kinetic cube with dynamic LED integration",
      "3D animated content narrating Saudi Arabia's mineral wealth story",
      "Exhibited in Germany",
    ],
    tools: ["Kinetic Systems", "LED Integration", "3D Content", "Mining Exhibition", "Germany"],
    featured: false,
    image: "/images/projects/maaden/thumbnail.jpg" as string | null,
    video: "https://www.youtube.com/watch?v=kKn_nX3JCNc",
    gallery: [] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "LEAP 2025",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "Large-scale experiential technology delivery at LEAP 2025 — Saudi Arabia's biggest tech conference, held in Riyadh. Fractal Systems delivered cutting-edge kinetic, LED, and interactive installations for leading brands across the show floor.",
    highlights: [
      "LEAP 2025 — Saudi Arabia's largest tech conference, Riyadh",
      "Multi-brand experiential builds across the show floor",
    ],
    tools: ["Kinetic Systems", "LED", "Interactive Tech", "Riyadh", "LEAP"],
    featured: false,
    image: "/images/projects/leap-2025/thumbnail.jpg" as string | null,
    video: "https://www.youtube.com/watch?v=17ot8ue-73M",
    gallery: [] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "GITEX Global — TII Anamorphic",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "Dual-screen anamorphic 3D illusion with precise perspective mapping for Technology Innovation Institute's stand at the world's largest tech exhibition, Dubai.",
    highlights: [
      "Dual-screen anamorphic 3D illusion with perspective precision",
      "Technology Innovation Institute — GITEX Dubai",
    ],
    tools: ["Anamorphic 3D", "LED Screens", "Perspective Mapping", "GITEX"],
    featured: false,
    image: "/images/projects/gitex-tii/thumbnail.jpg" as string | null,
    video: "https://www.youtube.com/watch?v=hf3OevSYNSg",
    gallery: [] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "Dubai Chamber of Commerce — Facade",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "Media facade illuminating the Dubai Chamber of Commerce building along Dubai Creek with dynamic colors and branded content. (Maintenance & logistics support role.)",
    highlights: [
      "Dynamic media facade on the Dubai Creek waterfront",
      "Branded content and architectural lighting integration",
    ],
    tools: ["LED Facade", "Facade Lighting", "Dubai Creek"],
    featured: false,
    image: null as string | null,
    video: "https://www.youtube.com/watch?v=sJMJrvtwo7I",
    gallery: [
      "/images/projects/dubai-chamber/photo-1.jpg",
      "/images/projects/dubai-chamber/photo-2.jpg",
      "/images/projects/dubai-chamber/photo-3.jpg",
      "/images/projects/dubai-chamber/photo-4.jpg",
      "/images/projects/dubai-chamber/photo-5.jpg",
      "/images/projects/dubai-chamber/photo-6.jpg",
      "/images/projects/dubai-chamber/photo-7.jpg",
      "/images/projects/dubai-chamber/photo-8.jpg",
      "/images/projects/dubai-chamber/photo-9.jpeg",
      "/images/projects/dubai-chamber/photo-10.jpeg",
      "/images/projects/dubai-chamber/photo-11.jpeg",
      "/images/projects/dubai-chamber/photo-12.jpeg",
    ] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "Cityscape Qatar — UDC",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "Dynamic synchronized moving screen walls and anamorphic 3D content — turning flat visuals into lifelike architectural illusions of futuristic developments for United Development Company, Doha.",
    highlights: [
      "Dynamic walls with synchronized moving screens",
      "Anamorphic 3D architectural illusions — UDC, Doha",
    ],
    tools: ["Moving Screens", "Anamorphic 3D", "Kinetic Walls", "Doha"],
    featured: false,
    image: "/images/projects/cityscape-qatar/thumbnail.jpg" as string | null,
    video: "https://www.youtube.com/watch?v=LZvtbwVU8sM",
    gallery: [
      "/images/projects/cityscape-qatar/thumbnail.jpg",
    ] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "HoloTubes — Holographic Display",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "Clear tubes housing 3D holograms — customizable for product showcases and brand activations at events across the GCC. Recurring technology offering deployed across multiple client events.",
    highlights: [
      "3D holograms in clear tube format — highly portable",
      "Deployed across multiple GCC events and brand activations",
    ],
    tools: ["Holographic Tech", "3D Display", "Brand Activations", "GCC"],
    featured: false,
    image: "/images/projects/holotube/thumbnail.jpg" as string | null,
    video: "https://www.youtube.com/watch?v=u0s0evbM5JA",
    gallery: [] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "Arabian Days Festival",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "2D animated projection content transforming traditional tables into interactive cultural displays — merging heritage aesthetics with immersive technology.",
    highlights: [
      "2D animated projection on custom table surfaces",
      "Cultural storytelling through interactive light and content",
    ],
    tools: ["Projection Mapping", "2D Animation", "Cultural Events"],
    featured: false,
    image: "/images/projects/arabian-days/thumbnail.jpg" as string | null,
    video: "https://www.youtube.com/watch?v=LPclIHb9Aq0",
    gallery: [] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "HMG — Global Health Exhibition 2024",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "2D animation and infographics on a custom kinetic ring for Habib Medical Group — making complex healthcare data visually engaging at Saudi Arabia's premier health conference.",
    highlights: [
      "Custom kinetic ring with live 2D animation & infographics",
      "Healthcare data visualization — Habib Medical Group, Riyadh",
    ],
    tools: ["Kinetic Ring", "2D Animation", "Healthcare", "Riyadh"],
    featured: false,
    image: "/images/projects/hmg-health/thumbnail.jpg" as string | null,
    video: "https://www.youtube.com/watch?v=wVXm1TwgEI8",
    gallery: [] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "Jumeirah Beach Lighting",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "LED screens and strip lights combining safety lighting with aesthetic appeal at JLT Beach, Dubai — permanent architectural lighting installation.",
    highlights: [
      "Permanent LED facade and strip lighting — JLT Beach Dubai",
      "Dual function: aesthetic appeal + safety lighting",
    ],
    tools: ["LED Lighting", "Facade Lighting", "Architectural Lighting", "Dubai"],
    featured: false,
    image: "/images/projects/jumeirah-beach/photo-1.png" as string | null,
    video: null as string | null,
    gallery: [
      "/images/projects/jumeirah-beach/photo-1.png",
      "/images/projects/jumeirah-beach/photo-2.png",
      "/images/projects/jumeirah-beach/photo-3.png",
      "/images/projects/jumeirah-beach/photo-4.png",
      "/images/projects/jumeirah-beach/photo-5.png",
    ] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "PureHealth — Arab Health 2024",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "Custom AV and experiential technology build for PureHealth at Arab Health 2024 — the Middle East's largest healthcare exhibition, held in Dubai.",
    highlights: [
      "Custom experiential build for PureHealth at Arab Health 2024",
      "Dubai World Trade Centre — largest healthcare exhibition in MENA",
    ],
    tools: ["LED Display", "AV Systems", "Healthcare", "Dubai"],
    featured: false,
    image: null as string | null,
    video: "https://www.youtube.com/watch?v=4IUqatlK16w",
    gallery: [] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "Innovo — Immersive Experience Room",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "Full-room immersive environment for Innovo — floor-to-ceiling projection and interactive content creating a 360° brand storytelling experience.",
    highlights: [
      "360° immersive room — floor-to-ceiling projection",
      "Interactive content and brand storytelling for Innovo",
    ],
    tools: ["Projection Mapping", "Immersive Room", "Interactive", "UAE"],
    featured: false,
    image: null as string | null,
    video: "https://www.youtube.com/watch?v=AAI0hpBYg1o",
    gallery: [] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "French National Day 🇫🇷 — Fractal Systems",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "Technology production for French National Day celebration — a 48-hour installation completed in under 22 hours, managing the full launching ceremony and all client-requested technology on behalf of Fractal Systems.",
    highlights: [
      "48-hour installation delivered in under 22 hours",
      "Full ceremony tech management — French National Day, UAE",
    ],
    tools: ["Event Technology", "Ceremony Production", "Fast-Track Install", "UAE"],
    featured: false,
    image: "/images/projects/french-national-day/photo-1.png" as string | null,
    video: null as string | null,
    gallery: [
      "/images/projects/french-national-day/photo-1.png",
      "/images/projects/french-national-day/photo-2.png",
    ] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "NEOM Sindalah Island — Monaco Yacht Show",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "Full experiential technology build for NEOM's Sindalah Island pavilion at Monaco Yacht Show 2024 — featuring a custom RFID interactive table with physical pucks, large-format LED walls, curved transparent displays, and LED ceiling strips. UHNW guests explored the island through touch-driven physical interaction, triggering destination content on surrounding screens.",
    highlights: [
      "Custom RFID interactive table — physical pucks trigger island content",
      "Large LED wall + curved transparent displays + LED ceiling strips",
      "Monaco Yacht Show 2024 — global UHNW & superyacht audience",
    ],
    tools: ["RFID Interactive Table", "LED Wall", "Transparent Displays", "NEOM", "Monaco"],
    featured: true,
    image: "/images/projects/neom-sindalah-monaco/photo-1.png" as string | null,
    video: null as string | null,
    gallery: [
      "/images/projects/neom-sindalah-monaco/photo-1.png",
      "/images/projects/neom-sindalah-monaco/photo-2.png",
      "/images/projects/neom-sindalah-monaco/photo-3.png",
      "/images/projects/neom-sindalah-monaco/photo-4.png",
      "/images/projects/neom-sindalah-monaco/photo-5.png",
      "/images/projects/neom-sindalah-monaco/photo-6.png",
      "/images/projects/neom-sindalah-monaco/photo-7.png",
    ] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "Immersive Room with LED Floor",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "Full immersive room featuring LED floor integration — walls, ceiling, and floor all come alive with synchronized content, creating a complete 360° digital environment.",
    highlights: [
      "Full immersive room — walls, ceiling and LED floor synchronized",
      "Complete 360° digital environment — Fractal Systems signature build",
    ],
    tools: ["LED Floor", "Immersive Room", "360° Display", "UAE"],
    featured: false,
    image: null as string | null,
    video: "https://www.youtube.com/watch?v=_YA9M1Kin_4",
    gallery: [] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "IKTVA Aramco — Projection Mapping",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "Large-scale projection mapping installation for IKTVA (In-Kingdom Total Value Add) — transforming physical structures into dynamic content canvases for Saudi Aramco's flagship industrial event.",
    highlights: [
      "Large-scale projection mapping — IKTVA Saudi Aramco",
      "Transforming physical surfaces into dynamic content canvases",
    ],
    tools: ["Projection Mapping", "Content Production", "IKTVA", "Saudi Arabia"],
    featured: false,
    image: null as string | null,
    video: "https://www.youtube.com/watch?v=W6Bab1Tnv8A",
    gallery: [] as string[],
    stat: null as { value: string; label: string } | null,
  },

  {
    title: "Multi-Curve LED Tunnel — ITHRA",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "Curved LED tunnel installation at King Abdulaziz Center for World Culture (ITHRA) — an immersive passageway of light blending art and technology in Saudi Arabia's cultural flagship.",
    highlights: [
      "Multi-curve LED tunnel — ITHRA King Abdulaziz Center",
      "Immersive walkthrough of light and curvature",
    ],
    tools: ["Curved LED", "Tunnel Installation", "ITHRA", "Saudi Arabia"],
    featured: false,
    image: null as string | null,
    video: "https://www.youtube.com/watch?v=Z-tmNS2p_XA",
    gallery: [] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "Kinetic Flowers — Saudi Spring Festival",
    company: "Fractal Systems",
    category: "Events & Production" as const,
    description: "A field of kinetic blooming flowers at Saudi Arabia's Spring Festival — mechanical petals that open, close, and dance in choreographed sequences, creating a living, breathing floral installation.",
    highlights: [
      "Kinetic blooming flowers — mechanical petals in choreographed motion",
      "Saudi Arabia Spring Festival — large-scale nature-inspired installation",
    ],
    tools: ["Kinetic Art", "Mechanical Flowers", "Saudi Festival", "KSA"],
    featured: false,
    image: null as string | null,
    video: "https://www.youtube.com/watch?v=8ju2vHGNZcs",
    gallery: [] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "Operations Portal",
    company: "Golden Sparrow Trading",
    category: "Operations & Systems" as const,
    description: "Built a comprehensive digital operations backbone from scratch — 11 business workflow phases covering Lead Capture to HR Hiring, with 280+ documented workflow nodes and 45+ standard operating procedures. Successfully pitched Odoo ERP implementation to automate all documented processes.",
    highlights: [
      "11 business workflow phases from Lead Capture to HR",
      "280+ documented workflow nodes across 9 departments",
      "45+ standard operating procedures created from scratch",
    ],
    tools: ["Process Design", "SOPs", "Odoo ERP", "Workflows", "Governance"],
    featured: true,
    image: null as string | null,
    video: null as string | null,
    gallery: [] as string[],
    stat: { value: "280+", label: "Workflow Nodes" },
  },
  {
    title: "Tender Monitoring System",
    company: "AI-Powered Automation",
    category: "Operations & Systems" as const,
    description: "Built automated tender tracking system for GCC markets using n8n workflows and AI. Monitors government procurement portals across UAE, KSA, and Oman — surfacing relevant opportunities in real-time.",
    highlights: [
      "Automated monitoring of GCC government procurement portals",
      "AI-powered opportunity filtering and classification",
    ],
    tools: ["n8n", "AI Automation", "Government Portals", "Tender Tracking"],
    featured: false,
    image: null as string | null,
    video: null as string | null,
    gallery: [] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "ESG & Compliance Suite",
    company: "Golden Sparrow Governance",
    category: "Operations & Systems" as const,
    description: "Authored complete governance documentation from scratch — ESG & Sustainability Policy, Anti-Bribery & Corruption Policy, Credit Policy, Code of Conduct, and HSE framework. All aligned with UAE regulations and international standards.",
    highlights: [
      "Full ESG, Anti-Bribery, Credit, and HSE policy suite",
      "Aligned with UAE regulations and international standards",
    ],
    tools: ["ESG Policy", "Compliance", "Governance", "UAE Regulations"],
    featured: false,
    image: null as string | null,
    video: null as string | null,
    gallery: [] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "Odoo ERP — Business Lead",
    company: "Golden Sparrow Trading",
    category: "Operations & Systems" as const,
    description: "Led the business requirements and process design for Odoo Enterprise ERP — mapped all departmental workflows, defined system requirements, and managed the implementation with Odoo's technical team across procurement, inventory, sales, and operations.",
    highlights: [
      "Mapped end-to-end business processes across all departments",
      "Defined system requirements and acceptance criteria for Odoo's implementation team",
    ],
    tools: ["Business Process Design", "Odoo ERP", "Requirements Documentation"],
    featured: false,
    image: null as string | null,
    video: null as string | null,
    gallery: [] as string[],
    stat: null as { value: string; label: string } | null,
  },
  {
    title: "Procurement Function — Built From Zero",
    company: "Golden Sparrow Trading",
    category: "Procurement & Tenders" as const,
    description: "Built the entire procurement and tendering function from scratch — SOPs, approval matrices, supplier portals, and compliance governance across UAE, KSA, and Oman.",
    highlights: [
      "Created all SOPs, policies, and governance documentation",
      "Designed a 4-layer legal framework for installment sales",
    ],
    tools: ["Policy Writing", "Portal Management", "Compliance"],
    featured: false,
    image: null as string | null,
    video: null as string | null,
    gallery: [] as string[],
    stat: null as { value: string; label: string } | null,
  },
] as const;

export type ProjectCategory = "Procurement & Tenders" | "Events & Production" | "Operations & Systems";

export const dailyStack = [
  {
    category: "ERP & Enterprise",
    icon: "🏢",
    tools: ["Oracle", "Odoo", "SAP", "Coupa"],
  },
  {
    category: "Government Portals",
    icon: "🏛️",
    tools: ["eSupply Dubai", "Etimad", "SABER", "Tenders on Time"],
  },
  {
    category: "Tendering & Sourcing",
    icon: "📋",
    tools: ["Tejari", "Ariba", "Jaggaer"],
  },
  {
    category: "Automation & AI",
    icon: "⚡",
    tools: ["n8n", "Claude", "ChatGPT", "Gemini", "Sora", "GLM", "Nano Banan"],
  },
  {
    category: "Analytics & Docs",
    icon: "📊",
    tools: ["Advanced Excel", "Power BI", "Mermaid Diagrams"],
  },
  {
    category: "Productivity",
    icon: "🔧",
    tools: ["MS Office", "Outlook", "Zoho", "Laserfiche", "Canva", "Notion", "ClickUp", "Monday", "Microsoft Teams", "Google Meet"],
  },
  {
    category: "Logistics & Shipping",
    icon: "🚚",
    tools: ["DHL", "FedEx", "Aramex"],
  },
] as const;

export const services = [
  {
    number: "01",
    title: "Procurement Function Setup",
    description: "I build procurement departments from scratch — sourcing workflows, approval matrices, vendor databases, and compliance governance. Done it twice, for two different industries.",
  },
  {
    number: "02",
    title: "Tender & Bid Management",
    description: "Full tender lifecycle — opportunity tracking, bid documentation, commercial proposals, and submission. Both buying side (sourcing) and selling side (winning contracts in GCC markets).",
  },
  {
    number: "03",
    title: "Cost Reduction & Sourcing",
    description: "Strategic sourcing that delivers measurable savings. AED 450K+ saved on a single project. 10-20% average reduction across 30+ events. I find where the money is hiding.",
  },
  {
    number: "04",
    title: "ERP Implementation (Odoo)",
    description: "Odoo Enterprise ERP setup — procurement, inventory, sales, and operations modules. Business requirements, gap analysis, and process design to go-live.",
  },
  {
    number: "05",
    title: "Operations & Compliance Setup",
    description: "SOPs, ESG policies, anti-bribery frameworks, credit policies, and governance documentation — all built from scratch and aligned with UAE regulations.",
  },
] as const;

export const certifications = [
  {
    name: "CIPS Level 4 Diploma in Procurement & Supply",
    institution: "Chartered Institute of Procurement & Supply",
    status: "in-progress" as const,
    detail: "Currently studying L4M3 & L4M2",
    year: "2025 — Present",
    progress: 25,
    totalModules: 8,
    completedModules: 2,
    verifyUrl: "http://credentials.cips.org/f132e284-43dc-46b1-84fe-bedd3a9a1999",
  },
  {
    name: "CIPS Ethical Procurement & Supply Certificate",
    institution: "Chartered Institute of Procurement & Supply",
    status: "completed" as const,
    detail: null,
    year: "2025",
    progress: null,
    totalModules: null,
    completedModules: null,
    verifyUrl: "http://credentials.cips.org/022a358f-e1db-4c6b-951b-0cb801aec532",
    badgeUrl: "https://eu.pdf.ms.credential.net/badge/image?env=eu-production&credential=ysceduey",
  },
  {
    name: "B.Sc. Accounting",
    institution: "Assiut University — Faculty of Commerce (English Section)",
    status: "completed" as const,
    detail: null,
    year: "2019",
    progress: null,
    totalModules: null,
    completedModules: null,
    verifyUrl: null,
  },
] as const;

export const testimonials = {
  intro: "My work puts me across suppliers, departments, and leadership simultaneously. Here's what they say.",
  items: [
    {
      name: "Avil Crasta",
      role: "Senior Sales Manager at Aoto",
      quote: "I had the pleasure of working closely with Mahmoud during a period where he was leading procurement for a highly specialized organization delivering complex solutions across high-end events, facade lighting, OOH LED deployments, and integrated automation systems. Mahmoud consistently demonstrated strong strategic thinking, commercial awareness, and a deep understanding of technically driven procurement. He was adept at managing multi-vendor ecosystems, negotiating under tight timelines, and ensuring that quality, compliance, and delivery schedules were never compromised despite the fast-paced and high-pressure nature of the projects. What stood out most was Mahmoud's ability to bridge the gap between technical teams, creative stakeholders, and suppliers. He understood not only the commercial aspects of procurement, but also the technical nuances of LED systems, control hardware, integration requirements, and site constraints making him a highly effective and trusted counterpart throughout our engagement. Mahmoud approaches procurement with professionalism, transparency, and a solution-oriented mindset. His structured approach, attention to detail, and commitment to long-term supplier relationships consistently added value to the projects we worked on together. I would confidently recommend Mahmoud for senior procurement or supply chain leadership roles, particularly in environments that demand technical depth, precision, and reliability alongside strong commercial judgment.",
    },
    {
      name: "Hanif Ullah",
      role: "Head of Project Management Office @ Fractal Systems",
      quote: "I had the pleasure of working with Mahmoud at Fractal Systems while I was Head of Project Management. Mahmoud consistently went above and beyond in supporting our projects — proactively finding solutions, assisting the team, and tackling procurement, logistics, and lead-time challenges with a calm and structured approach. His problem-solving mindset and reliability made a real difference to project delivery, even under pressure. It was truly a delight working with him, and I highly recommend Mahmoud as a procurement professional.",
    },
    {
      name: "Iffat Iqbal",
      role: "Head of Human Resources & Expert Talent Acquisition - MENA Region",
      quote: "I worked with Mahmoud at Fractal, and I always appreciated how dependable and steady he was in his role. He handled procurement tasks with a calm, professional approach and was very good at managing suppliers and following up on details without needing reminders. What I liked most is that Mahmoud was easy to work with — polite, cooperative, and someone you could trust to complete whatever was assigned to him. He doesn't overcomplicate things and gets the job done. I'm happy to recommend him, and I'm sure he will add value wherever he goes next.",
    },
    {
      name: "Mohsin Bilal",
      role: "Group Chief Financial Officer | Finance Director",
      quote: "I had the pleasure of working with Mahmoud, and he consistently impressed me with his dedication, reliability, and strong problem-solving skills. He's a great communicator, a supportive team player, and someone who always delivers high-quality work. Mahmoud's positive attitude and professionalism make him an asset to any team, and I highly recommend him.",
    },
    {
      name: "Huda Muhammad",
      role: "Senior Project Manager | Global Corporate & Experiential Events",
      quote: "I am pleased to recommend Abdallah, who has been an outstanding Procurement Manager at Fractal. His ability to source materials efficiently, negotiate with suppliers, and provide timely support made him an invaluable part of our operations. Abdallah consistently demonstrated professionalism, reliability, and a strong problem-solving mindset. His support played a major role in ensuring our projects were delivered smoothly and on schedule. Any team would be lucky to have him.",
    },
  ],
  linkedinUrl: "https://www.linkedin.com/in/mahmoudf-abdallah",
} as const;

export const contactTypes = [
  { type: "hiring", label: "Hiring", description: "Full-time or contract opportunities" },
  { type: "freelance", label: "Part-time / Freelance", description: "Contract, part-time, or freelance engagement" },
  { type: "consulting", label: "Consulting", description: "Expert advisory & implementation" },
  { type: "collab", label: "Collaboration", description: "Let's build something together" },
  { type: "hello", label: "Say Hi", description: "Just want to connect" },
] as const;

export const industries = [
  { name: "Heavy Equipment", company: "Golden Sparrow Trading" },
  { name: "Construction Equipment", company: "Golden Sparrow Trading" },
  { name: "FMCG", company: "Americana Foods" },
  { name: "Food & Beverage", company: "Americana Foods" },
  { name: "Event Technology", company: "Fractal Systems" },
  { name: "Façade Lighting", company: "Fractal Systems" },
  { name: "Audio Visual", company: "Fractal Systems" },
  { name: "Exhibition Management", company: "Fractal Systems" },
  { name: "LED & Kinetic Displays", company: "Fractal Systems" },
  { name: "Oil & Gas", company: "Hafa Trading" },
  { name: "Industrial Supplies", company: "Hafa Trading" },
  { name: "MEP", company: "Hafa Trading" },
  { name: "PPE", company: "Hafa Trading" },
  { name: "E-Commerce", company: "Saudi Supplier" },
  { name: "FMCG Retail", company: "Egyptian Army Stores" },
  { name: "AI & Machine Learning", company: "TELUS Int'l · Appen · Figure Eight · CrowdFlower · Lionbridge AI" },
] as const;
