// ============ PORTFOLIO PROJECTS DATA ============
// Source of truth for the /projects page and detail pages
// Images stored in public/projects/[slug]/

export type ProjectCategory = "mega-events" | "interactive-immersive" | "facade-lighting" | "led-display";

export interface PortfolioProject {
  slug: string;
  title: string;
  client: string;
  location: string;
  year: string;
  category: ProjectCategory;
  description: string;
  technologies: string[];
  hero: string | null;
  gallery: string[];
  youtube_embed: string;
  has_images: boolean;
  references: Record<string, string>;
}

export const projectCategories: Record<ProjectCategory, string> = {
  "mega-events": "Mega Events & Exhibitions",
  "interactive-immersive": "Interactive & Immersive",
  "facade-lighting": "Facade Lighting",
  "led-display": "LED Display Systems",
};

export const projectCategoryColors: Record<ProjectCategory, string> = {
  "mega-events": "#f59e0b",
  "interactive-immersive": "#06b6d4",
  "facade-lighting": "#10b981",
  "led-display": "#3b82f6",
};

export const projectCategoryIcons: Record<ProjectCategory, string> = {
  "mega-events": "🎪",
  "interactive-immersive": "🎮",
  "facade-lighting": "🏙️",
  "led-display": "📺",
};

export const portfolioProjects: PortfolioProject[] = [
  {
    slug: "elie-saab-1001-seasons",
    title: "1001 Seasons of Elie Saab",
    client: "Elie Saab / Diriyah Season",
    location: "Riyadh, KSA",
    year: "2024",
    category: "mega-events",
    description: "10 massive 12-meter rotating LED towers for the award-winning fashion show featuring Celine Dion and Jennifer Lopez. Won 'Best Use of Technology' at Saudi Event Awards.",
    technologies: ["Rotating LED Triangles", "Kinetic Towers", "Immersive Staging"],
    hero: "elie-saab-1001-seasons/hero.jpg",
    gallery: ["elie-saab-1001-seasons/elie-saab-award-winning.jpg", "elie-saab-1001-seasons/elie-saab-immersive.jpg"],
    youtube_embed: "https://www.youtube.com/embed/Mbk9Pr_Lklk",
    has_images: true,
    references: {
      website: "https://www.fractalsystems.ae/event-technologies",
      youtube: "https://www.youtube.com/watch?v=Mbk9Pr_Lklk",
    },
  },
  {
    slug: "jetex-led-cube-cop28",
    title: "JETEX LED Cube — COP28",
    client: "JETEX / COP28",
    location: "Dubai, UAE",
    year: "2023",
    category: "led-display",
    description: "World's largest LED cube — 10m × 10m × 10m, 600 sqm LED surface. Designed, manufactured and installed in just 7 days for COP28.",
    technologies: ["LED Cube", "Anamorphic Content", "Facade Engineering"],
    hero: "jetex-led-cube-cop28/hero.png",
    gallery: [
      "jetex-led-cube-cop28/jetex-cube-installation-crane.png",
      "jetex-led-cube-cop28/jetex-cube-night-exterior.png",
      "jetex-led-cube-cop28/jetex-cube-red-lights-night.jpeg",
      "jetex-led-cube-cop28/jetex-cube-panoramic-wide.png",
    ],
    youtube_embed: "",
    has_images: true,
    references: {
      website: "https://www.facadelighting.com/jetex-cube",
    },
  },
  {
    slug: "world-defense-show-2024",
    title: "World Defense Show 2024",
    client: "WDS",
    location: "Riyadh, KSA",
    year: "2024",
    category: "mega-events",
    description: "16m × 3m × 7m LED tunnel, 3D Anamorphic Corner Displays, and custom LED Helmet masterpiece. Complete engineering, hardware, content, and implementation.",
    technologies: ["LED Tunnel", "Anamorphic Displays", "Custom LED Helmet", "3D Animation"],
    hero: "world-defense-show-2024/hero.jpeg",
    gallery: [
      "world-defense-show-2024/wds-3d-animation.jpeg",
      "world-defense-show-2024/wds-robotics.webp",
    ],
    youtube_embed: "https://www.youtube.com/embed/_IqtpIDb-6E",
    has_images: true,
    references: {
      website: "https://www.fractaldigital.ae",
      youtube: "https://youtu.be/_IqtpIDb-6E",
    },
  },
  {
    slug: "iktva-aramco-2023",
    title: "IKTVA 2023 — Saudi Aramco",
    client: "Saudi Aramco / IKTVA",
    location: "Dammam, KSA",
    year: "2023",
    category: "mega-events",
    description: "DNA Xs rotating totems (768 LED panels), 360° projection mapping on arm sculpture, Interactive LED Ribbon, Tangible Tables, and Robotic Hospitality.",
    technologies: ["DNA Xs Totems", "Projection Mapping", "LED Ring Display", "Tangible Tables", "Robotic Hospitality"],
    hero: "iktva-aramco-2023/hero.png",
    gallery: [
      "iktva-aramco-2023/iktva-aramco-projection.png",
      "iktva-aramco-2023/iktva-innovative-ceiling.png",
    ],
    youtube_embed: "https://www.youtube.com/embed/W6Bab1Tnv8A",
    has_images: true,
    references: {
      website: "https://www.fractaldigital.ae/projects",
      youtube: "https://youtu.be/W6Bab1Tnv8A",
    },
  },
  {
    slug: "cop16-riyadh",
    title: "COP16 Riyadh — UNCCD",
    client: "UNCCD",
    location: "Riyadh, KSA",
    year: "2024",
    category: "interactive-immersive",
    description: "Projection mapping room, interactive pressure tiles, AR tablets for exploring digital content over real displays.",
    technologies: ["Projection Mapping", "Interactive Pressure Tiles", "AR Tablets", "Sliding AR Tables"],
    hero: "cop16-riyadh/hero.png",
    gallery: [
      "cop16-riyadh/cop16-exhibition.png",
      "cop16-riyadh/cop16-ar-tablets.png",
    ],
    youtube_embed: "https://www.youtube.com/embed/zT4BY9Vz23s",
    has_images: true,
    references: {
      website: "https://www.fractaldigital.ae",
      youtube: "https://youtu.be/zT4BY9Vz23s",
    },
  },
  {
    slug: "dubai-chamber-facade",
    title: "Dubai Chamber of Commerce — Facade",
    client: "Dubai Chamber of Commerce",
    location: "Dubai, UAE",
    year: "2022",
    category: "facade-lighting",
    description: "5,300+ pixel dot LED fixtures along Dubai Creek with 10km cabling for stunning media facade.",
    technologies: ["Pixel Dot LED", "Media Facade", "10km Cabling"],
    hero: "dubai-chamber-facade/hero.jpg",
    gallery: [
      "dubai-chamber-facade/dubai-chamber-installation-workers.jpg",
      "dubai-chamber-facade/dubai-chamber-night-closeup.jpg",
      "dubai-chamber-facade/dubai-chamber-facade-green.jpg",
      "dubai-chamber-facade/dubai-chamber-wide-night.jpg",
    ],
    youtube_embed: "",
    has_images: true,
    references: {
      website: "https://www.facadelighting.com/dubai-chamber",
    },
  },
  {
    slug: "bank-albilad-facade",
    title: "Bank Al Bilad — Riyadh Facade",
    client: "Bank Al Bilad",
    location: "Riyadh, KSA",
    year: "2025",
    category: "facade-lighting",
    description: "52-meter LED Media Facade using flexible LED strips on iconic bank headquarters.",
    technologies: ["Flexible LED Strips", "Media Facade", "52m Installation"],
    hero: "bank-albilad-facade/hero.png",
    gallery: [
      "bank-albilad-facade/bank-albilad-facade-night.jpeg",
      "bank-albilad-facade/bank-albilad-night-1.jpeg",
      "bank-albilad-facade/bank-albilad-night-2.jpeg",
      "bank-albilad-facade/bank-albilad-night-3.jpeg",
      "bank-albilad-facade/bank-albilad-render.png",
    ],
    youtube_embed: "https://www.youtube.com/embed/Gq9lWsSYU-k",
    has_images: true,
    references: {
      website: "https://www.facadelighting.com/bank-albilad",
      youtube: "https://youtu.be/Gq9lWsSYU-k",
    },
  },
  {
    slug: "jumeirah-lighting-towers",
    title: "Jumeirah Lighting Towers",
    client: "Dubai Municipality",
    location: "Dubai, UAE",
    year: "2024",
    category: "facade-lighting",
    description: "800 meters of facade lighting with LED screens and LED strip lights for beach area and night swimmer visibility at Kite Beach.",
    technologies: ["Facade Lighting", "LED Screens", "Beach Safety Lighting"],
    hero: "jumeirah-lighting-towers/hero.png",
    gallery: [
      "jumeirah-lighting-towers/jumeirah-tower-sunset.png",
      "jumeirah-lighting-towers/jumeirah-tower-beach-view.png",
      "jumeirah-lighting-towers/jumeirah-tower-led-display.png",
      "jumeirah-lighting-towers/jumeirah-tower-closeup.png",
    ],
    youtube_embed: "",
    has_images: true,
    references: {
      website: "https://www.facadelighting.com/jumeirah-lighting-towers",
    },
  },
  {
    slug: "iktva-2025",
    title: "IKTVA 2025 — Saudi Aramco",
    client: "Saudi Aramco / IKTVA",
    location: "Riyadh, KSA",
    year: "2025",
    category: "mega-events",
    description: "Anamorphic Display showcasing Aramco's '1st Made in Kingdom Products', Kinetic Triangle Room, Transparent Mesh Room, LED tunnels.",
    technologies: ["Anamorphic Display", "Kinetic Triangles", "Transparent Mesh", "LED Tunnels"],
    hero: "iktva-2025/hero.png",
    gallery: ["iktva-2025/iktva-anamorphic-content.png"],
    youtube_embed: "https://www.youtube.com/embed/VMfeyqfny68",
    has_images: true,
    references: {
      website: "https://www.fractaldigital.ae",
      youtube: "https://youtu.be/VMfeyqfny68",
    },
  },
  {
    slug: "holotubes",
    title: "HoloTube Technology Showcase",
    client: "Fractal Systems",
    location: "UAE",
    year: "2024",
    category: "interactive-immersive",
    description: "Cylindrical holographic displays with gesture recognition — modern way to display 3D holograms inside clear tubes.",
    technologies: ["HoloTubes", "Holographic Display", "Gesture Recognition"],
    hero: "holotubes/hero.png",
    gallery: ["holotubes/holotubes-holographic.png"],
    youtube_embed: "https://www.youtube.com/embed/u0s0evbM5JA",
    has_images: true,
    references: {
      website: "https://www.fractaldigital.ae/holographic-content",
      youtube: "https://youtu.be/u0s0evbM5JA",
    },
  },
  {
    slug: "leap-2024",
    title: "LEAP 2024 — Digital Saudi",
    client: "Digital Saudi",
    location: "Riyadh, KSA",
    year: "2024",
    category: "interactive-immersive",
    description: "Transparent OLED Sliding Screen, Kinetic Ceiling with spheres and blades, AI-powered interactive systems.",
    technologies: ["Transparent OLED", "Kinetic Ceiling", "Sliding Screens", "AI Systems"],
    hero: "leap-2024/hero.png",
    gallery: [
      "leap-2024/leap-infographics.png",
      "leap-2024/leap-digital-saudi-stand.jpg",
      "leap-2024/leap-interactive.webp",
    ],
    youtube_embed: "https://www.youtube.com/embed/HIxihJJNP3E",
    has_images: true,
    references: {
      website: "https://www.fractalsystems.ae/kinetic-ceiling",
      youtube: "https://youtu.be/HIxihJJNP3E",
    },
  },
  {
    slug: "purehealth-arab-health",
    title: "PureHealth — Arab Health 2024",
    client: "PureHealth",
    location: "Dubai, UAE",
    year: "2024",
    category: "interactive-immersive",
    description: "10m diameter circular LED screen, LED Globe, 400+ sqm of LEDs for healthcare exhibition.",
    technologies: ["Circular LED Screen", "LED Globe", "Custom Displays"],
    hero: "purehealth-arab-health/hero.webp",
    gallery: [],
    youtube_embed: "",
    has_images: true,
    references: {},
  },
  {
    slug: "cityscape-qatar-udc",
    title: "Cityscape Qatar 2024 — UDC",
    client: "United Development Company",
    location: "Doha, Qatar",
    year: "2024",
    category: "interactive-immersive",
    description: "AI chatbot (Arabic/English), kinetic wall, RFID interactive table for real estate showcase.",
    technologies: ["AI Chatbot", "Dynamic Wall", "RFID Table", "Kinetic Wall"],
    hero: "cityscape-qatar-udc/hero.png",
    gallery: [
      "cityscape-qatar-udc/cityscape-udc-exhibition.png",
      "cityscape-qatar-udc/cityscape-anamorphic.avif",
    ],
    youtube_embed: "",
    has_images: true,
    references: {},
  },
  {
    slug: "nba-district-abudhabi",
    title: "NBA District — Abu Dhabi 2024",
    client: "ADQ / NBA",
    location: "Abu Dhabi, UAE",
    year: "2024",
    category: "interactive-immersive",
    description: "Interactive basketball game experience with LED floors and walls.",
    technologies: ["Interactive Floor", "LED Walls", "Body Tracking", "Sports Gaming"],
    hero: "nba-district-abudhabi/hero.jpg",
    gallery: ["nba-district-abudhabi/nba-district-basketball-game.jpg"],
    youtube_embed: "",
    has_images: true,
    references: {
      website: "https://www.fractalsystems.ae/entertainment-engagement",
    },
  },
  {
    slug: "gitex-2023-tii",
    title: "GITEX 2023 — TII",
    client: "Technology Innovation Institute",
    location: "Dubai, UAE",
    year: "2023",
    category: "interactive-immersive",
    description: "Two 10m × 2.5m Anamorphic Displays, Ceiling LED Displays, LED Floors, and AI-powered Interactive Experience.",
    technologies: ["Anamorphic Displays", "LED Floor", "Ceiling LED", "AI Chatbot"],
    hero: null,
    gallery: [],
    youtube_embed: "https://www.youtube.com/embed/hf3OevSYNSg",
    has_images: false,
    references: {
      website: "https://www.fractalsystems.ae/anamorphic-content",
      youtube: "https://youtu.be/hf3OevSYNSg",
    },
  },
  {
    slug: "hmg-arab-health-2025",
    title: "HMG — Arab Health 2025",
    client: "Habib Medical Group",
    location: "Dubai, UAE",
    year: "2025",
    category: "interactive-immersive",
    description: "Interactive LED screens, AI chatbot, Kinetic DNA XS for medical exhibition.",
    technologies: ["Kinetic DNA XS", "AI Chatbot", "Interactive LED"],
    hero: "hmg-arab-health-2025/hero.png",
    gallery: ["hmg-arab-health-2025/hmg-arab-health-exhibition.png"],
    youtube_embed: "",
    has_images: true,
    references: {},
  },
  {
    slug: "arabian-days-festival",
    title: "Arabian Days Festival 2024",
    client: "Abu Dhabi Arabic Language Centre",
    location: "Abu Dhabi, UAE",
    year: "2024",
    category: "interactive-immersive",
    description: "Interactive Projection Table with LED display for cultural festival.",
    technologies: ["Interactive Projection Table", "LED Display"],
    hero: "arabian-days-festival/hero.png",
    gallery: [],
    youtube_embed: "",
    has_images: true,
    references: {},
  },
  {
    slug: "maaden-mining",
    title: "Ma'aden — Mining Exhibition 2024",
    client: "Ma'aden",
    location: "Germany",
    year: "2024",
    category: "interactive-immersive",
    description: "Multi-level Kinetic Cube with immersive experience showcasing Saudi Arabia's mineral story.",
    technologies: ["Kinetic Cube", "3D Animation", "Immersive Experience"],
    hero: "maaden-mining/hero.jpeg",
    gallery: [],
    youtube_embed: "",
    has_images: true,
    references: {},
  },
  {
    slug: "red-sea-global",
    title: "Red Sea Global Experience Center",
    client: "Red Sea Global",
    location: "KSA",
    year: "2025",
    category: "interactive-immersive",
    description: "Immersive experience center with projection mapping for luxury tourism showcase.",
    technologies: ["Projection Mapping", "Immersive Experience", "Permanent Installation"],
    hero: "red-sea-global/hero.png",
    gallery: [],
    youtube_embed: "",
    has_images: true,
    references: {
      website: "https://www.fractalsystems.ae/permanent-installations",
    },
  },
  {
    slug: "purehealth-global-health",
    title: "PureHealth — Global Health Week",
    client: "PureHealth",
    location: "Abu Dhabi, UAE",
    year: "2024",
    category: "interactive-immersive",
    description: "Immersive LED tunnel experience for global health exhibition.",
    technologies: ["LED Tunnel", "Immersive Experience", "2D Animation"],
    hero: "purehealth-global-health/hero.png",
    gallery: [
      "purehealth-global-health/global-health-2d-animation.png",
      "purehealth-global-health/lean-global-health.webp",
    ],
    youtube_embed: "",
    has_images: true,
    references: {},
  },
  {
    slug: "modon-food-show-2025",
    title: "Modon — Saudi Food Show 2025",
    client: "Modon",
    location: "Riyadh, KSA",
    year: "2025",
    category: "interactive-immersive",
    description: "LED Ribbon, Kinetic DNA XS, Transparent OLED for Vision 2030 exhibition.",
    technologies: ["LED Ribbon", "Kinetic DNA XS", "Transparent OLED"],
    hero: "modon-food-show-2025/hero.jpg",
    gallery: [],
    youtube_embed: "",
    has_images: true,
    references: {},
  },
  {
    slug: "book-fair-abudhabi-2025",
    title: "Abu Dhabi International Book Fair 2025",
    client: "Abu Dhabi Arabic Language Centre",
    location: "Abu Dhabi, UAE",
    year: "2025",
    category: "interactive-immersive",
    description: "Laser Room experience for international book fair.",
    technologies: ["Laser Room", "Immersive Experience"],
    hero: "book-fair-abudhabi-2025/hero.png",
    gallery: [],
    youtube_embed: "",
    has_images: true,
    references: {},
  },
  {
    slug: "moiat-facade",
    title: "MOIAT — Facade Lighting",
    client: "Ministry of Industry & Advanced Technology",
    location: "Dubai, UAE",
    year: "2024",
    category: "facade-lighting",
    description: "Facade lighting for Ministry of Industry building — in process.",
    technologies: ["Facade Lighting", "LED Strips"],
    hero: "moiat-facade/hero.png",
    gallery: [],
    youtube_embed: "",
    has_images: true,
    references: {
      website: "https://www.facadelighting.com/projects",
    },
  },
  {
    slug: "leap-2025",
    title: "LEAP 2025",
    client: "Various",
    location: "Riyadh, KSA",
    year: "2025",
    category: "interactive-immersive",
    description: "LED tunnel, vertical sliding screen, AI chatbots, Kinetic DNA XS, hologram displays.",
    technologies: ["LED Tunnel", "Sliding Screen", "AI Chatbot", "Kinetic DNA XS", "Hologram"],
    hero: null,
    gallery: [],
    youtube_embed: "",
    has_images: false,
    references: {},
  },
  {
    slug: "saudi-cup-2024",
    title: "Saudi Cup 2024 — MOC Show",
    client: "Ministry of Culture",
    location: "Riyadh, KSA",
    year: "2024",
    category: "mega-events",
    description: "20-minute entertainment show celebrating Arabian horses for the Saudi Cup horse racing event.",
    technologies: ["LED Show", "Stage Technology", "Opening Ceremony"],
    hero: null,
    gallery: [],
    youtube_embed: "",
    has_images: false,
    references: {},
  },
  {
    slug: "mamzar-beach-lighting",
    title: "Al Mamzar Beach Night Lighting",
    client: "Dubai Municipality",
    location: "Dubai, UAE",
    year: "2024",
    category: "facade-lighting",
    description: "300m night swimming beach illumination and 5km LED walkway as part of AED 400M beach development.",
    technologies: ["Beach Lighting", "LED Walkway", "Night Swimming Illumination"],
    hero: null,
    gallery: [],
    youtube_embed: "",
    has_images: false,
    references: {},
  },
  {
    slug: "sharjah-light-festival",
    title: "Sharjah Light Festival",
    client: "Sharjah Tourism",
    location: "Sharjah, UAE",
    year: "2024",
    category: "facade-lighting",
    description: "Festival-scale facade and architectural lighting for Sharjah Light Festival.",
    technologies: ["Projection Mapping", "Facade Lighting"],
    hero: null,
    gallery: [],
    youtube_embed: "",
    has_images: false,
    references: {},
  },
  {
    slug: "monaco-yacht-neom",
    title: "Monaco Yacht Show — NEOM Sindalah",
    client: "NEOM",
    location: "Monaco",
    year: "2024",
    category: "interactive-immersive",
    description: "Luxury tourism showcase for NEOM's Sindalah Island at Monaco Yacht Show.",
    technologies: ["Immersive Experience", "Luxury Showcase"],
    hero: null,
    gallery: [],
    youtube_embed: "",
    has_images: false,
    references: {},
  },
];

export const showreels = [
  {
    title: "Ask Us the Impossible — Ep. 1",
    youtube_embed: "https://www.youtube.com/embed/d_WBUPegHP0",
    thumbnail: "/projects/_showreels/ask-impossible-ep1.jpg",
  },
  {
    title: "Ask Us the Impossible — Ep. 2",
    youtube_embed: "https://www.youtube.com/embed/eUI8k1CijhI",
    thumbnail: "/projects/_showreels/ask-impossible-ep2.jpg",
  },
  {
    title: "Animation Showreels",
    youtube_embed: "https://www.youtube.com/embed/hOZd0KQYxXE",
    thumbnail: "/projects/_showreels/animation-showreel.jpg",
  },
];

export function getProjectBySlug(slug: string): PortfolioProject | undefined {
  return portfolioProjects.find((p) => p.slug === slug);
}

export function getProjectsByCategory(category: ProjectCategory): PortfolioProject[] {
  return portfolioProjects.filter((p) => p.category === category);
}

export function getProjectImagePath(imagePath: string): string {
  return `/projects/${imagePath}`;
}
